language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew
  
script:  
  - ./gradlew assembleRelease