version: 2

# Disable emulator audio
machine:
  environment:
    QEMU_AUDIO_DRV: none

test:
  pre:
    - emulator -avd circleci-android24 -no-window:
        background: true
        parallel: true
    - circle-android wait-for-boot

jobs:
  build:
    working_directory: ~/workspace
    environment:
          JVM_OPTS: -Xmx4096m
          ANDROID_API_LEVEL: 27
          EMULATOR_API_LEVEL: 22
          ANDROID_ABI: armeabi-v7a
          ANDROID_TAG: google_apis
          ANDROID_TARGET: android-$ANDROID_API_LEVEL
          ADB_INSTALL_TIMEOUT: 20 # minutes (2 minutes by default)
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradlew
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
          environment:
            TERM: dumb
      - run:
          name: Generate JaCoCo report
          command: ./gradlew jacocoTestReport
          environment:
            TERM: dumb
      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
          environment:
            TERM: dumb
      - store_artifacts:
          path: app/build/reports
          destination: reports
          environment:
            TERM: dumb
      - store_test_results:
          path: app/build/test-results
          environment:
            TERM: dumb
